import "@/styles/globals.css";
// Space here to keep global.css import at top.
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export const metadata: Metadata = {
  title: "Cryptopals Crypto Challenges",
  description: "An enhanced clone of the orignal Cryptopals Crypto Challeneges wesbite generated by grad students for USM.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
